// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rsuncitychain/taxpayments/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTaxpaymentRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetTaxpaymentRequest) Reset()         { *m = QueryGetTaxpaymentRequest{} }
func (m *QueryGetTaxpaymentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaxpaymentRequest) ProtoMessage()    {}
func (*QueryGetTaxpaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{2}
}
func (m *QueryGetTaxpaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTaxpaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTaxpaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTaxpaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaxpaymentRequest.Merge(m, src)
}
func (m *QueryGetTaxpaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTaxpaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaxpaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaxpaymentRequest proto.InternalMessageInfo

func (m *QueryGetTaxpaymentRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetTaxpaymentResponse struct {
	Taxpayment Taxpayment `protobuf:"bytes,1,opt,name=taxpayment,proto3" json:"taxpayment"`
}

func (m *QueryGetTaxpaymentResponse) Reset()         { *m = QueryGetTaxpaymentResponse{} }
func (m *QueryGetTaxpaymentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaxpaymentResponse) ProtoMessage()    {}
func (*QueryGetTaxpaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{3}
}
func (m *QueryGetTaxpaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTaxpaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTaxpaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTaxpaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaxpaymentResponse.Merge(m, src)
}
func (m *QueryGetTaxpaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTaxpaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaxpaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaxpaymentResponse proto.InternalMessageInfo

func (m *QueryGetTaxpaymentResponse) GetTaxpayment() Taxpayment {
	if m != nil {
		return m.Taxpayment
	}
	return Taxpayment{}
}

type QueryAllTaxpaymentRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTaxpaymentRequest) Reset()         { *m = QueryAllTaxpaymentRequest{} }
func (m *QueryAllTaxpaymentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTaxpaymentRequest) ProtoMessage()    {}
func (*QueryAllTaxpaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{4}
}
func (m *QueryAllTaxpaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTaxpaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTaxpaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTaxpaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTaxpaymentRequest.Merge(m, src)
}
func (m *QueryAllTaxpaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTaxpaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTaxpaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTaxpaymentRequest proto.InternalMessageInfo

func (m *QueryAllTaxpaymentRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTaxpaymentResponse struct {
	Taxpayment []Taxpayment        `protobuf:"bytes,1,rep,name=taxpayment,proto3" json:"taxpayment"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTaxpaymentResponse) Reset()         { *m = QueryAllTaxpaymentResponse{} }
func (m *QueryAllTaxpaymentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTaxpaymentResponse) ProtoMessage()    {}
func (*QueryAllTaxpaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7654aef033aae941, []int{5}
}
func (m *QueryAllTaxpaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTaxpaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTaxpaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTaxpaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTaxpaymentResponse.Merge(m, src)
}
func (m *QueryAllTaxpaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTaxpaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTaxpaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTaxpaymentResponse proto.InternalMessageInfo

func (m *QueryAllTaxpaymentResponse) GetTaxpayment() []Taxpayment {
	if m != nil {
		return m.Taxpayment
	}
	return nil
}

func (m *QueryAllTaxpaymentResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "rsuncitychain.taxpayments.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "rsuncitychain.taxpayments.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetTaxpaymentRequest)(nil), "rsuncitychain.taxpayments.v1.QueryGetTaxpaymentRequest")
	proto.RegisterType((*QueryGetTaxpaymentResponse)(nil), "rsuncitychain.taxpayments.v1.QueryGetTaxpaymentResponse")
	proto.RegisterType((*QueryAllTaxpaymentRequest)(nil), "rsuncitychain.taxpayments.v1.QueryAllTaxpaymentRequest")
	proto.RegisterType((*QueryAllTaxpaymentResponse)(nil), "rsuncitychain.taxpayments.v1.QueryAllTaxpaymentResponse")
}

func init() {
	proto.RegisterFile("rsuncitychain/taxpayments/v1/query.proto", fileDescriptor_7654aef033aae941)
}

var fileDescriptor_7654aef033aae941 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x8a, 0x13, 0x31,
	0x18, 0xc7, 0x9b, 0x75, 0xb7, 0xb0, 0x11, 0x05, 0x63, 0x0f, 0x3a, 0x2c, 0xa3, 0x86, 0x75, 0xb7,
	0x2e, 0x36, 0x71, 0x56, 0x44, 0xc1, 0x93, 0x3d, 0xd8, 0x8b, 0xc8, 0x3a, 0x78, 0xf2, 0x20, 0xa4,
	0x35, 0x8c, 0x81, 0x36, 0x99, 0x6d, 0xd2, 0xd2, 0x22, 0x5e, 0x7c, 0x02, 0x41, 0xf0, 0xe2, 0x0b,
	0x78, 0x14, 0xc1, 0x83, 0x6f, 0xb0, 0xc7, 0x05, 0x2f, 0x9e, 0x44, 0x5a, 0xc1, 0xd7, 0x90, 0x26,
	0xd1, 0xe9, 0xd8, 0x3a, 0x4e, 0xd9, 0x4b, 0x49, 0xd2, 0xef, 0xff, 0xfd, 0x7f, 0x99, 0xef, 0x3f,
	0x03, 0xeb, 0x7d, 0x3d, 0x90, 0x1d, 0x61, 0xc6, 0x9d, 0xe7, 0x4c, 0x48, 0x6a, 0xd8, 0x28, 0x65,
	0xe3, 0x1e, 0x97, 0x46, 0xd3, 0x61, 0x44, 0x0f, 0x07, 0xbc, 0x3f, 0x26, 0x69, 0x5f, 0x19, 0x85,
	0xb6, 0x72, 0x95, 0x64, 0xae, 0x92, 0x0c, 0xa3, 0xe0, 0x1c, 0xeb, 0x09, 0xa9, 0xa8, 0xfd, 0x75,
	0x82, 0xa0, 0x96, 0xa8, 0x44, 0xd9, 0x25, 0x9d, 0xad, 0xfc, 0xe9, 0x56, 0xa2, 0x54, 0xd2, 0xe5,
	0x94, 0xa5, 0x82, 0x32, 0x29, 0x95, 0x61, 0x46, 0x28, 0xa9, 0xfd, 0xbf, 0x7b, 0x1d, 0xa5, 0x7b,
	0x4a, 0xd3, 0x36, 0xd3, 0xdc, 0xb9, 0xd3, 0x61, 0xd4, 0xe6, 0x86, 0x45, 0x34, 0x65, 0x89, 0x90,
	0xb6, 0xd8, 0xd7, 0x5e, 0x2b, 0x44, 0x4f, 0x59, 0x9f, 0xf5, 0x7e, 0xb7, 0x6d, 0x14, 0x96, 0x66,
	0x5b, 0x57, 0x8e, 0x6b, 0x10, 0x3d, 0x9a, 0x79, 0x1f, 0xd8, 0x1e, 0x31, 0x3f, 0x1c, 0x70, 0x6d,
	0xf0, 0x53, 0x78, 0x3e, 0x77, 0xaa, 0x53, 0x25, 0x35, 0x47, 0x2d, 0x58, 0x75, 0x5e, 0x17, 0xc0,
	0x65, 0x50, 0x3f, 0xbd, 0xbf, 0x4d, 0x8a, 0x1e, 0x14, 0x71, 0xea, 0xe6, 0xe6, 0xd1, 0xb7, 0x4b,
	0x95, 0xf7, 0x3f, 0x3f, 0xec, 0x81, 0xd8, 0xcb, 0x71, 0x04, 0x2f, 0xda, 0xfe, 0x2d, 0x6e, 0x1e,
	0xff, 0xd1, 0x78, 0x73, 0x54, 0x83, 0x1b, 0x42, 0x3e, 0xe3, 0x23, 0x6b, 0xb2, 0x19, 0xbb, 0x0d,
	0xee, 0xc2, 0x60, 0x99, 0xc4, 0x93, 0x3d, 0x84, 0x30, 0x33, 0xf7, 0x74, 0xf5, 0x62, 0xba, 0xac,
	0x4b, 0x73, 0x7d, 0x46, 0x18, 0xcf, 0x75, 0xc0, 0x1d, 0x0f, 0x78, 0xaf, 0xdb, 0x5d, 0x04, 0xbc,
	0x0f, 0x61, 0x36, 0x21, 0x6f, 0xb6, 0x43, 0xdc, 0x38, 0xc9, 0x6c, 0x9c, 0xc4, 0x85, 0xc9, 0x8f,
	0x93, 0x1c, 0xb0, 0x84, 0x7b, 0x6d, 0x3c, 0xa7, 0xc4, 0x9f, 0x80, 0xbf, 0xd3, 0x5f, 0x2e, 0xff,
	0xb8, 0xd3, 0xa9, 0x93, 0xdd, 0x09, 0xb5, 0x72, 0xd8, 0x6b, 0x16, 0x7b, 0xf7, 0xbf, 0xd8, 0x0e,
	0x66, 0x9e, 0x7b, 0xff, 0xed, 0x3a, 0xdc, 0xb0, 0xdc, 0xe8, 0x1d, 0x80, 0x55, 0x37, 0x65, 0x74,
	0xa3, 0x98, 0x6c, 0x31, 0x64, 0x41, 0xb4, 0x82, 0xc2, 0x51, 0xe0, 0xeb, 0xaf, 0xbe, 0xfc, 0x78,
	0xb3, 0xb6, 0x83, 0xb6, 0x69, 0x89, 0x17, 0x02, 0x7d, 0x06, 0xf0, 0x4c, 0x2e, 0x2e, 0xe8, 0x76,
	0x09, 0xcb, 0x65, 0x99, 0x0c, 0xee, 0xac, 0x2e, 0xf4, 0xc8, 0xb7, 0x2c, 0x32, 0x45, 0x8d, 0x02,
	0xe4, 0x6c, 0x4d, 0x5f, 0xd8, 0xb4, 0xbf, 0x44, 0x1f, 0x01, 0x3c, 0xfb, 0x40, 0xe8, 0x55, 0xe1,
	0x97, 0xe5, 0xb5, 0x14, 0xfc, 0xd2, 0x08, 0xe2, 0x86, 0x85, 0xdf, 0x45, 0x57, 0x4b, 0xc1, 0x37,
	0xef, 0x1e, 0x4d, 0x42, 0x70, 0x3c, 0x09, 0xc1, 0xf7, 0x49, 0x08, 0x5e, 0x4f, 0xc3, 0xca, 0xf1,
	0x34, 0xac, 0x7c, 0x9d, 0x86, 0x95, 0x27, 0x57, 0xf2, 0xfa, 0x51, 0xbe, 0xc3, 0x38, 0xe5, 0xba,
	0x5d, 0xb5, 0x1f, 0xa4, 0x9b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xbe, 0x3e, 0x6a, 0xa7,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Taxpayment items.
	GetTaxpayment(ctx context.Context, in *QueryGetTaxpaymentRequest, opts ...grpc.CallOption) (*QueryGetTaxpaymentResponse, error)
	ListTaxpayment(ctx context.Context, in *QueryAllTaxpaymentRequest, opts ...grpc.CallOption) (*QueryAllTaxpaymentResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.taxpayments.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTaxpayment(ctx context.Context, in *QueryGetTaxpaymentRequest, opts ...grpc.CallOption) (*QueryGetTaxpaymentResponse, error) {
	out := new(QueryGetTaxpaymentResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.taxpayments.v1.Query/GetTaxpayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListTaxpayment(ctx context.Context, in *QueryAllTaxpaymentRequest, opts ...grpc.CallOption) (*QueryAllTaxpaymentResponse, error) {
	out := new(QueryAllTaxpaymentResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.taxpayments.v1.Query/ListTaxpayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Taxpayment items.
	GetTaxpayment(context.Context, *QueryGetTaxpaymentRequest) (*QueryGetTaxpaymentResponse, error)
	ListTaxpayment(context.Context, *QueryAllTaxpaymentRequest) (*QueryAllTaxpaymentResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetTaxpayment(ctx context.Context, req *QueryGetTaxpaymentRequest) (*QueryGetTaxpaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxpayment not implemented")
}
func (*UnimplementedQueryServer) ListTaxpayment(ctx context.Context, req *QueryAllTaxpaymentRequest) (*QueryAllTaxpaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaxpayment not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.taxpayments.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTaxpayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTaxpaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTaxpayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.taxpayments.v1.Query/GetTaxpayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTaxpayment(ctx, req.(*QueryGetTaxpaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListTaxpayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTaxpaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTaxpayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.taxpayments.v1.Query/ListTaxpayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTaxpayment(ctx, req.(*QueryAllTaxpaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rsuncitychain.taxpayments.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetTaxpayment",
			Handler:    _Query_GetTaxpayment_Handler,
		},
		{
			MethodName: "ListTaxpayment",
			Handler:    _Query_ListTaxpayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsuncitychain/taxpayments/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTaxpaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTaxpaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTaxpaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTaxpaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTaxpaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTaxpaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Taxpayment.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTaxpaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTaxpaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTaxpaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTaxpaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTaxpaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTaxpaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Taxpayment) > 0 {
		for iNdEx := len(m.Taxpayment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Taxpayment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTaxpaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTaxpaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Taxpayment.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTaxpaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTaxpaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Taxpayment) > 0 {
		for _, e := range m.Taxpayment {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTaxpaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTaxpaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTaxpaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTaxpaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTaxpaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTaxpaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taxpayment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Taxpayment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTaxpaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTaxpaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTaxpaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTaxpaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTaxpaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTaxpaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taxpayment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taxpayment = append(m.Taxpayment, Taxpayment{})
			if err := m.Taxpayment[len(m.Taxpayment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
