// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rsuncitychain/landregistration/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateLandrecord struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index               string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	LandRegNum          string `protobuf:"bytes,3,opt,name=landRegNum,proto3" json:"landRegNum,omitempty"`
	OwnerAddress        string `protobuf:"bytes,4,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
	LandLocationAddress string `protobuf:"bytes,5,opt,name=landLocationAddress,proto3" json:"landLocationAddress,omitempty"`
	LandOwnerName       string `protobuf:"bytes,6,opt,name=landOwnerName,proto3" json:"landOwnerName,omitempty"`
	DateofLandPurchase  string `protobuf:"bytes,7,opt,name=dateofLandPurchase,proto3" json:"dateofLandPurchase,omitempty"`
	NameOfPreviousOwner string `protobuf:"bytes,8,opt,name=nameOfPreviousOwner,proto3" json:"nameOfPreviousOwner,omitempty"`
	LandOwnerTel        string `protobuf:"bytes,9,opt,name=landOwnerTel,proto3" json:"landOwnerTel,omitempty"`
	LandOwnerEmail      string `protobuf:"bytes,10,opt,name=landOwnerEmail,proto3" json:"landOwnerEmail,omitempty"`
	Tx                  string `protobuf:"bytes,11,opt,name=tx,proto3" json:"tx,omitempty"`
	CreatedAt           string `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *MsgCreateLandrecord) Reset()         { *m = MsgCreateLandrecord{} }
func (m *MsgCreateLandrecord) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLandrecord) ProtoMessage()    {}
func (*MsgCreateLandrecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{2}
}
func (m *MsgCreateLandrecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLandrecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLandrecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLandrecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLandrecord.Merge(m, src)
}
func (m *MsgCreateLandrecord) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLandrecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLandrecord.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLandrecord proto.InternalMessageInfo

func (m *MsgCreateLandrecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateLandrecord) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgCreateLandrecord) GetLandRegNum() string {
	if m != nil {
		return m.LandRegNum
	}
	return ""
}

func (m *MsgCreateLandrecord) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *MsgCreateLandrecord) GetLandLocationAddress() string {
	if m != nil {
		return m.LandLocationAddress
	}
	return ""
}

func (m *MsgCreateLandrecord) GetLandOwnerName() string {
	if m != nil {
		return m.LandOwnerName
	}
	return ""
}

func (m *MsgCreateLandrecord) GetDateofLandPurchase() string {
	if m != nil {
		return m.DateofLandPurchase
	}
	return ""
}

func (m *MsgCreateLandrecord) GetNameOfPreviousOwner() string {
	if m != nil {
		return m.NameOfPreviousOwner
	}
	return ""
}

func (m *MsgCreateLandrecord) GetLandOwnerTel() string {
	if m != nil {
		return m.LandOwnerTel
	}
	return ""
}

func (m *MsgCreateLandrecord) GetLandOwnerEmail() string {
	if m != nil {
		return m.LandOwnerEmail
	}
	return ""
}

func (m *MsgCreateLandrecord) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *MsgCreateLandrecord) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type MsgCreateLandrecordResponse struct {
}

func (m *MsgCreateLandrecordResponse) Reset()         { *m = MsgCreateLandrecordResponse{} }
func (m *MsgCreateLandrecordResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLandrecordResponse) ProtoMessage()    {}
func (*MsgCreateLandrecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{3}
}
func (m *MsgCreateLandrecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLandrecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLandrecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLandrecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLandrecordResponse.Merge(m, src)
}
func (m *MsgCreateLandrecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLandrecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLandrecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLandrecordResponse proto.InternalMessageInfo

type MsgUpdateLandrecord struct {
	Creator             string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index               string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	LandRegNum          string `protobuf:"bytes,3,opt,name=landRegNum,proto3" json:"landRegNum,omitempty"`
	OwnerAddress        string `protobuf:"bytes,4,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
	LandLocationAddress string `protobuf:"bytes,5,opt,name=landLocationAddress,proto3" json:"landLocationAddress,omitempty"`
	LandOwnerName       string `protobuf:"bytes,6,opt,name=landOwnerName,proto3" json:"landOwnerName,omitempty"`
	DateofLandPurchase  string `protobuf:"bytes,7,opt,name=dateofLandPurchase,proto3" json:"dateofLandPurchase,omitempty"`
	NameOfPreviousOwner string `protobuf:"bytes,8,opt,name=nameOfPreviousOwner,proto3" json:"nameOfPreviousOwner,omitempty"`
	LandOwnerTel        string `protobuf:"bytes,9,opt,name=landOwnerTel,proto3" json:"landOwnerTel,omitempty"`
	LandOwnerEmail      string `protobuf:"bytes,10,opt,name=landOwnerEmail,proto3" json:"landOwnerEmail,omitempty"`
	Tx                  string `protobuf:"bytes,11,opt,name=tx,proto3" json:"tx,omitempty"`
	CreatedAt           string `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *MsgUpdateLandrecord) Reset()         { *m = MsgUpdateLandrecord{} }
func (m *MsgUpdateLandrecord) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLandrecord) ProtoMessage()    {}
func (*MsgUpdateLandrecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{4}
}
func (m *MsgUpdateLandrecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLandrecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLandrecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLandrecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLandrecord.Merge(m, src)
}
func (m *MsgUpdateLandrecord) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLandrecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLandrecord.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLandrecord proto.InternalMessageInfo

func (m *MsgUpdateLandrecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetLandRegNum() string {
	if m != nil {
		return m.LandRegNum
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetLandLocationAddress() string {
	if m != nil {
		return m.LandLocationAddress
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetLandOwnerName() string {
	if m != nil {
		return m.LandOwnerName
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetDateofLandPurchase() string {
	if m != nil {
		return m.DateofLandPurchase
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetNameOfPreviousOwner() string {
	if m != nil {
		return m.NameOfPreviousOwner
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetLandOwnerTel() string {
	if m != nil {
		return m.LandOwnerTel
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetLandOwnerEmail() string {
	if m != nil {
		return m.LandOwnerEmail
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *MsgUpdateLandrecord) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type MsgUpdateLandrecordResponse struct {
}

func (m *MsgUpdateLandrecordResponse) Reset()         { *m = MsgUpdateLandrecordResponse{} }
func (m *MsgUpdateLandrecordResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLandrecordResponse) ProtoMessage()    {}
func (*MsgUpdateLandrecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{5}
}
func (m *MsgUpdateLandrecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLandrecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLandrecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLandrecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLandrecordResponse.Merge(m, src)
}
func (m *MsgUpdateLandrecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLandrecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLandrecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLandrecordResponse proto.InternalMessageInfo

type MsgDeleteLandrecord struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index   string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *MsgDeleteLandrecord) Reset()         { *m = MsgDeleteLandrecord{} }
func (m *MsgDeleteLandrecord) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLandrecord) ProtoMessage()    {}
func (*MsgDeleteLandrecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{6}
}
func (m *MsgDeleteLandrecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLandrecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLandrecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLandrecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLandrecord.Merge(m, src)
}
func (m *MsgDeleteLandrecord) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLandrecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLandrecord.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLandrecord proto.InternalMessageInfo

func (m *MsgDeleteLandrecord) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteLandrecord) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type MsgDeleteLandrecordResponse struct {
}

func (m *MsgDeleteLandrecordResponse) Reset()         { *m = MsgDeleteLandrecordResponse{} }
func (m *MsgDeleteLandrecordResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteLandrecordResponse) ProtoMessage()    {}
func (*MsgDeleteLandrecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2aef272d4b36077, []int{7}
}
func (m *MsgDeleteLandrecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteLandrecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteLandrecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteLandrecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteLandrecordResponse.Merge(m, src)
}
func (m *MsgDeleteLandrecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteLandrecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteLandrecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteLandrecordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "rsuncitychain.landregistration.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "rsuncitychain.landregistration.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateLandrecord)(nil), "rsuncitychain.landregistration.v1.MsgCreateLandrecord")
	proto.RegisterType((*MsgCreateLandrecordResponse)(nil), "rsuncitychain.landregistration.v1.MsgCreateLandrecordResponse")
	proto.RegisterType((*MsgUpdateLandrecord)(nil), "rsuncitychain.landregistration.v1.MsgUpdateLandrecord")
	proto.RegisterType((*MsgUpdateLandrecordResponse)(nil), "rsuncitychain.landregistration.v1.MsgUpdateLandrecordResponse")
	proto.RegisterType((*MsgDeleteLandrecord)(nil), "rsuncitychain.landregistration.v1.MsgDeleteLandrecord")
	proto.RegisterType((*MsgDeleteLandrecordResponse)(nil), "rsuncitychain.landregistration.v1.MsgDeleteLandrecordResponse")
}

func init() {
	proto.RegisterFile("rsuncitychain/landregistration/v1/tx.proto", fileDescriptor_d2aef272d4b36077)
}

var fileDescriptor_d2aef272d4b36077 = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xf6, 0x93, 0x78, 0x65, 0x80, 0x37, 0x69, 0x5e, 0x81, 0x30, 0x2a, 0x34, 0x8d, 0x4a,
	0x24, 0x5b, 0x91, 0x76, 0xd8, 0x01, 0xb1, 0x0d, 0x6e, 0xfb, 0xa5, 0x0c, 0x2e, 0x5c, 0x90, 0x49,
	0xbc, 0x2c, 0x52, 0x13, 0x57, 0xb6, 0x3b, 0xba, 0x0b, 0x42, 0x1c, 0x77, 0xe2, 0xcf, 0xe0, 0x38,
	0x09, 0xfe, 0x88, 0x49, 0x5c, 0x26, 0x4e, 0x1c, 0x10, 0x42, 0xdb, 0x61, 0xff, 0x06, 0xb2, 0x9d,
	0xb4, 0x4b, 0xda, 0xa9, 0x2d, 0xdc, 0x10, 0x97, 0xaa, 0xfe, 0xde, 0xf7, 0x9e, 0xbf, 0xcf, 0xef,
	0xc5, 0x06, 0x15, 0xc6, 0x1b, 0xb1, 0x17, 0x8a, 0x43, 0x6f, 0x1f, 0x87, 0xb1, 0x53, 0xc3, 0xb1,
	0xcf, 0x48, 0x10, 0x72, 0xc1, 0xb0, 0x08, 0x69, 0xec, 0x1c, 0x2c, 0x39, 0xa2, 0x69, 0xd7, 0x19,
	0x15, 0x14, 0xde, 0xcf, 0x70, 0xed, 0x3c, 0xd7, 0x3e, 0x58, 0x2a, 0xdd, 0xc2, 0x51, 0x18, 0x53,
	0x47, 0xfd, 0xea, 0xac, 0xd2, 0x8c, 0x47, 0x79, 0x44, 0xb9, 0x13, 0xf1, 0x40, 0x56, 0x8b, 0x78,
	0x90, 0x04, 0x66, 0x75, 0xe0, 0xb5, 0x5a, 0x39, 0x7a, 0x91, 0x84, 0xa6, 0x03, 0x1a, 0x50, 0x8d,
	0xcb, 0x7f, 0x09, 0x6a, 0xf7, 0xd6, 0x5a, 0xc7, 0x0c, 0x47, 0x69, 0x95, 0x6a, 0x6f, 0xbe, 0xc6,
	0x3c, 0xca, 0x7c, 0x9d, 0x53, 0xfe, 0x61, 0x80, 0x1b, 0x9b, 0x3c, 0x78, 0x59, 0xf7, 0xb1, 0x20,
	0x3b, 0xaa, 0x1a, 0x5c, 0x06, 0x26, 0x6e, 0x88, 0x7d, 0xca, 0x42, 0x71, 0x88, 0x8c, 0x39, 0x63,
	0xc1, 0x5c, 0x43, 0xdf, 0xbe, 0x3c, 0x9a, 0x4e, 0x24, 0xaf, 0xfa, 0x3e, 0x23, 0x9c, 0xef, 0x0a,
	0x16, 0xc6, 0x81, 0xdb, 0xa6, 0xc2, 0x0d, 0x30, 0xa6, 0xf5, 0xa0, 0xa1, 0x39, 0x63, 0x61, 0xa2,
	0xfa, 0xd0, 0xee, 0x79, 0x80, 0xb6, 0xde, 0x72, 0xcd, 0x3c, 0xf9, 0x79, 0xaf, 0xf0, 0xe9, 0xe2,
	0xb8, 0x62, 0xb8, 0x49, 0x8d, 0x95, 0xf5, 0x0f, 0x17, 0xc7, 0x95, 0x76, 0xf5, 0xa3, 0x8b, 0xe3,
	0xca, 0x62, 0xd6, 0x60, 0xb3, 0xd3, 0x62, 0xce, 0x4a, 0x79, 0x16, 0xcc, 0xe4, 0x20, 0x97, 0xf0,
	0x3a, 0x8d, 0x39, 0x29, 0x7f, 0x1d, 0x06, 0x53, 0x9b, 0x3c, 0x58, 0x67, 0x04, 0x0b, 0xb2, 0xd1,
	0x3a, 0x17, 0x88, 0xc0, 0xb8, 0x27, 0x31, 0xca, 0xb4, 0x77, 0x37, 0x5d, 0xc2, 0x69, 0x30, 0x1a,
	0xc6, 0x3e, 0x69, 0x2a, 0x7b, 0xa6, 0xab, 0x17, 0xd0, 0x02, 0x40, 0xca, 0x70, 0x49, 0xb0, 0xd5,
	0x88, 0xd0, 0xb0, 0x0a, 0x5d, 0x42, 0x60, 0x19, 0x14, 0xe9, 0xdb, 0x98, 0xb0, 0xe4, 0xd8, 0xd0,
	0x88, 0x62, 0x64, 0x30, 0xb8, 0x08, 0xa6, 0x64, 0xc6, 0x06, 0xf5, 0x94, 0x8d, 0x94, 0x3a, 0xaa,
	0xa8, 0xdd, 0x42, 0xf0, 0x01, 0xb8, 0x2e, 0xe1, 0x6d, 0x59, 0x65, 0x0b, 0x47, 0x04, 0x8d, 0x29,
	0x6e, 0x16, 0x84, 0x36, 0x80, 0xd2, 0x39, 0xdd, 0x93, 0xfe, 0x76, 0x1a, 0xcc, 0xdb, 0xc7, 0x9c,
	0xa0, 0x71, 0x45, 0xed, 0x12, 0x91, 0x3a, 0x62, 0x1c, 0x91, 0xed, 0xbd, 0x1d, 0x46, 0x0e, 0x42,
	0xda, 0xe0, 0xaa, 0x14, 0xba, 0xa6, 0x75, 0x74, 0x09, 0x49, 0x77, 0xad, 0x2d, 0x5f, 0x90, 0x1a,
	0x32, 0xb5, 0xbb, 0xcb, 0x18, 0x9c, 0x07, 0x93, 0xad, 0xf5, 0xf3, 0x08, 0x87, 0x35, 0x04, 0x14,
	0x2b, 0x87, 0xc2, 0x49, 0x30, 0x24, 0x9a, 0x68, 0x42, 0xc5, 0x86, 0x44, 0x13, 0xde, 0x01, 0xa6,
	0x3a, 0x7a, 0xe2, 0xaf, 0x0a, 0x54, 0x54, 0x70, 0x1b, 0x58, 0x29, 0xca, 0xf9, 0x48, 0x7b, 0x53,
	0xbe, 0x0b, 0x6e, 0x77, 0x69, 0x66, 0xbe, 0xd9, 0x7a, 0x10, 0xfe, 0x37, 0xfb, 0x9f, 0x68, 0x76,
	0xbe, 0x99, 0xad, 0x66, 0xef, 0xaa, 0x5e, 0x3f, 0x23, 0x35, 0xf2, 0x37, 0xbd, 0xee, 0xba, 0x67,
	0xbe, 0x68, 0xba, 0x67, 0xf5, 0xf3, 0x08, 0x18, 0xde, 0xe4, 0x01, 0x7c, 0x07, 0x8a, 0x99, 0xbb,
	0xb4, 0xda, 0xc7, 0x1d, 0x98, 0xbb, 0xa1, 0x4a, 0x2b, 0x83, 0xe7, 0xa4, 0x3a, 0xe0, 0x91, 0x01,
	0x6e, 0x76, 0x5c, 0x69, 0xcb, 0xfd, 0x15, 0xcc, 0xe7, 0x95, 0x9e, 0xfc, 0x59, 0x5e, 0x46, 0x4c,
	0xc7, 0x27, 0xb7, 0x3c, 0x88, 0xbb, 0xc1, 0xc5, 0x5c, 0x35, 0x15, 0x4a, 0x4c, 0xc7, 0x4c, 0xf4,
	0x29, 0x26, 0x9f, 0xd7, 0xaf, 0x98, 0xab, 0xc6, 0xa5, 0x34, 0xfa, 0x5e, 0xbe, 0x75, 0x6b, 0x4f,
	0x4f, 0xce, 0x2c, 0xe3, 0xf4, 0xcc, 0x32, 0x7e, 0x9d, 0x59, 0xc6, 0xc7, 0x73, 0xab, 0x70, 0x7a,
	0x6e, 0x15, 0xbe, 0x9f, 0x5b, 0x85, 0x57, 0xf3, 0x3d, 0x9f, 0x3a, 0x71, 0x58, 0x27, 0xfc, 0xcd,
	0x98, 0x7a, 0xc6, 0x1f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x22, 0xf7, 0xff, 0xd8, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateLandrecord(ctx context.Context, in *MsgCreateLandrecord, opts ...grpc.CallOption) (*MsgCreateLandrecordResponse, error)
	UpdateLandrecord(ctx context.Context, in *MsgUpdateLandrecord, opts ...grpc.CallOption) (*MsgUpdateLandrecordResponse, error)
	DeleteLandrecord(ctx context.Context, in *MsgDeleteLandrecord, opts ...grpc.CallOption) (*MsgDeleteLandrecordResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.landregistration.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLandrecord(ctx context.Context, in *MsgCreateLandrecord, opts ...grpc.CallOption) (*MsgCreateLandrecordResponse, error) {
	out := new(MsgCreateLandrecordResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.landregistration.v1.Msg/CreateLandrecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLandrecord(ctx context.Context, in *MsgUpdateLandrecord, opts ...grpc.CallOption) (*MsgUpdateLandrecordResponse, error) {
	out := new(MsgUpdateLandrecordResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.landregistration.v1.Msg/UpdateLandrecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteLandrecord(ctx context.Context, in *MsgDeleteLandrecord, opts ...grpc.CallOption) (*MsgDeleteLandrecordResponse, error) {
	out := new(MsgDeleteLandrecordResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.landregistration.v1.Msg/DeleteLandrecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateLandrecord(context.Context, *MsgCreateLandrecord) (*MsgCreateLandrecordResponse, error)
	UpdateLandrecord(context.Context, *MsgUpdateLandrecord) (*MsgUpdateLandrecordResponse, error)
	DeleteLandrecord(context.Context, *MsgDeleteLandrecord) (*MsgDeleteLandrecordResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateLandrecord(ctx context.Context, req *MsgCreateLandrecord) (*MsgCreateLandrecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLandrecord not implemented")
}
func (*UnimplementedMsgServer) UpdateLandrecord(ctx context.Context, req *MsgUpdateLandrecord) (*MsgUpdateLandrecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLandrecord not implemented")
}
func (*UnimplementedMsgServer) DeleteLandrecord(ctx context.Context, req *MsgDeleteLandrecord) (*MsgDeleteLandrecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLandrecord not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.landregistration.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLandrecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLandrecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLandrecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.landregistration.v1.Msg/CreateLandrecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLandrecord(ctx, req.(*MsgCreateLandrecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLandrecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLandrecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLandrecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.landregistration.v1.Msg/UpdateLandrecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLandrecord(ctx, req.(*MsgUpdateLandrecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteLandrecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteLandrecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteLandrecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.landregistration.v1.Msg/DeleteLandrecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteLandrecord(ctx, req.(*MsgDeleteLandrecord))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rsuncitychain.landregistration.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateLandrecord",
			Handler:    _Msg_CreateLandrecord_Handler,
		},
		{
			MethodName: "UpdateLandrecord",
			Handler:    _Msg_UpdateLandrecord_Handler,
		},
		{
			MethodName: "DeleteLandrecord",
			Handler:    _Msg_DeleteLandrecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsuncitychain/landregistration/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateLandrecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLandrecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLandrecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LandOwnerEmail) > 0 {
		i -= len(m.LandOwnerEmail)
		copy(dAtA[i:], m.LandOwnerEmail)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerEmail)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LandOwnerTel) > 0 {
		i -= len(m.LandOwnerTel)
		copy(dAtA[i:], m.LandOwnerTel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerTel)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.NameOfPreviousOwner) > 0 {
		i -= len(m.NameOfPreviousOwner)
		copy(dAtA[i:], m.NameOfPreviousOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NameOfPreviousOwner)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DateofLandPurchase) > 0 {
		i -= len(m.DateofLandPurchase)
		copy(dAtA[i:], m.DateofLandPurchase)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DateofLandPurchase)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LandOwnerName) > 0 {
		i -= len(m.LandOwnerName)
		copy(dAtA[i:], m.LandOwnerName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LandLocationAddress) > 0 {
		i -= len(m.LandLocationAddress)
		copy(dAtA[i:], m.LandLocationAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandLocationAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LandRegNum) > 0 {
		i -= len(m.LandRegNum)
		copy(dAtA[i:], m.LandRegNum)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandRegNum)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLandrecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLandrecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLandrecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLandrecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLandrecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLandrecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Tx) > 0 {
		i -= len(m.Tx)
		copy(dAtA[i:], m.Tx)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tx)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LandOwnerEmail) > 0 {
		i -= len(m.LandOwnerEmail)
		copy(dAtA[i:], m.LandOwnerEmail)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerEmail)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LandOwnerTel) > 0 {
		i -= len(m.LandOwnerTel)
		copy(dAtA[i:], m.LandOwnerTel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerTel)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.NameOfPreviousOwner) > 0 {
		i -= len(m.NameOfPreviousOwner)
		copy(dAtA[i:], m.NameOfPreviousOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NameOfPreviousOwner)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DateofLandPurchase) > 0 {
		i -= len(m.DateofLandPurchase)
		copy(dAtA[i:], m.DateofLandPurchase)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DateofLandPurchase)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LandOwnerName) > 0 {
		i -= len(m.LandOwnerName)
		copy(dAtA[i:], m.LandOwnerName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandOwnerName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LandLocationAddress) > 0 {
		i -= len(m.LandLocationAddress)
		copy(dAtA[i:], m.LandLocationAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandLocationAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LandRegNum) > 0 {
		i -= len(m.LandRegNum)
		copy(dAtA[i:], m.LandRegNum)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LandRegNum)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLandrecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLandrecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLandrecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLandrecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLandrecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLandrecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteLandrecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteLandrecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteLandrecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateLandrecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandRegNum)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandLocationAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DateofLandPurchase)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NameOfPreviousOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerTel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerEmail)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLandrecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateLandrecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandRegNum)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandLocationAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DateofLandPurchase)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NameOfPreviousOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerTel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LandOwnerEmail)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tx)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateLandrecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteLandrecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteLandrecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLandrecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLandrecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLandrecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandRegNum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandRegNum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandLocationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandLocationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateofLandPurchase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DateofLandPurchase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameOfPreviousOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NameOfPreviousOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerTel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerTel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLandrecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLandrecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLandrecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLandrecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLandrecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLandrecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandRegNum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandRegNum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandLocationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandLocationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateofLandPurchase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DateofLandPurchase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameOfPreviousOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NameOfPreviousOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerTel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerTel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandOwnerEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LandOwnerEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLandrecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLandrecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLandrecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLandrecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLandrecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLandrecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteLandrecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteLandrecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteLandrecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
