// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rsuncitychain/individualregistration/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetIndividualrecordRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetIndividualrecordRequest) Reset()         { *m = QueryGetIndividualrecordRequest{} }
func (m *QueryGetIndividualrecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetIndividualrecordRequest) ProtoMessage()    {}
func (*QueryGetIndividualrecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{2}
}
func (m *QueryGetIndividualrecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetIndividualrecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetIndividualrecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetIndividualrecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetIndividualrecordRequest.Merge(m, src)
}
func (m *QueryGetIndividualrecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetIndividualrecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetIndividualrecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetIndividualrecordRequest proto.InternalMessageInfo

func (m *QueryGetIndividualrecordRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetIndividualrecordResponse struct {
	Individualrecord Individualrecord `protobuf:"bytes,1,opt,name=individualrecord,proto3" json:"individualrecord"`
}

func (m *QueryGetIndividualrecordResponse) Reset()         { *m = QueryGetIndividualrecordResponse{} }
func (m *QueryGetIndividualrecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetIndividualrecordResponse) ProtoMessage()    {}
func (*QueryGetIndividualrecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{3}
}
func (m *QueryGetIndividualrecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetIndividualrecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetIndividualrecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetIndividualrecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetIndividualrecordResponse.Merge(m, src)
}
func (m *QueryGetIndividualrecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetIndividualrecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetIndividualrecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetIndividualrecordResponse proto.InternalMessageInfo

func (m *QueryGetIndividualrecordResponse) GetIndividualrecord() Individualrecord {
	if m != nil {
		return m.Individualrecord
	}
	return Individualrecord{}
}

type QueryAllIndividualrecordRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllIndividualrecordRequest) Reset()         { *m = QueryAllIndividualrecordRequest{} }
func (m *QueryAllIndividualrecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllIndividualrecordRequest) ProtoMessage()    {}
func (*QueryAllIndividualrecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{4}
}
func (m *QueryAllIndividualrecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllIndividualrecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllIndividualrecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllIndividualrecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllIndividualrecordRequest.Merge(m, src)
}
func (m *QueryAllIndividualrecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllIndividualrecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllIndividualrecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllIndividualrecordRequest proto.InternalMessageInfo

func (m *QueryAllIndividualrecordRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllIndividualrecordResponse struct {
	Individualrecord []Individualrecord  `protobuf:"bytes,1,rep,name=individualrecord,proto3" json:"individualrecord"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllIndividualrecordResponse) Reset()         { *m = QueryAllIndividualrecordResponse{} }
func (m *QueryAllIndividualrecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllIndividualrecordResponse) ProtoMessage()    {}
func (*QueryAllIndividualrecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e4ab12a9ba57be, []int{5}
}
func (m *QueryAllIndividualrecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllIndividualrecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllIndividualrecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllIndividualrecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllIndividualrecordResponse.Merge(m, src)
}
func (m *QueryAllIndividualrecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllIndividualrecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllIndividualrecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllIndividualrecordResponse proto.InternalMessageInfo

func (m *QueryAllIndividualrecordResponse) GetIndividualrecord() []Individualrecord {
	if m != nil {
		return m.Individualrecord
	}
	return nil
}

func (m *QueryAllIndividualrecordResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "rsuncitychain.individualregistration.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "rsuncitychain.individualregistration.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetIndividualrecordRequest)(nil), "rsuncitychain.individualregistration.v1.QueryGetIndividualrecordRequest")
	proto.RegisterType((*QueryGetIndividualrecordResponse)(nil), "rsuncitychain.individualregistration.v1.QueryGetIndividualrecordResponse")
	proto.RegisterType((*QueryAllIndividualrecordRequest)(nil), "rsuncitychain.individualregistration.v1.QueryAllIndividualrecordRequest")
	proto.RegisterType((*QueryAllIndividualrecordResponse)(nil), "rsuncitychain.individualregistration.v1.QueryAllIndividualrecordResponse")
}

func init() {
	proto.RegisterFile("rsuncitychain/individualregistration/v1/query.proto", fileDescriptor_b8e4ab12a9ba57be)
}

var fileDescriptor_b8e4ab12a9ba57be = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xb1, 0x6e, 0x13, 0x31,
	0x18, 0xc7, 0xe3, 0x42, 0x22, 0xd5, 0x2c, 0xe0, 0x66, 0x40, 0x11, 0xba, 0x56, 0x1e, 0x28, 0xaa,
	0x90, 0xad, 0x6b, 0x11, 0x05, 0x81, 0x22, 0xc8, 0x90, 0x52, 0x89, 0xa1, 0xdc, 0xc8, 0xe6, 0x24,
	0xd6, 0x61, 0x91, 0xd8, 0xd7, 0xb3, 0x13, 0x35, 0x42, 0x2c, 0xbc, 0x00, 0x48, 0xbc, 0x04, 0x6c,
	0x3c, 0x00, 0x0f, 0xd0, 0xb1, 0x12, 0x4b, 0x27, 0x84, 0x12, 0x24, 0x06, 0x36, 0x9e, 0x00, 0xc5,
	0x76, 0x45, 0x72, 0xcd, 0x95, 0x4b, 0xa1, 0x4b, 0xe4, 0xd8, 0xf7, 0xff, 0x7f, 0xff, 0xdf, 0xf9,
	0xfb, 0x0e, 0x6e, 0xa5, 0xba, 0x2f, 0xdb, 0xc2, 0x0c, 0xdb, 0x2f, 0x98, 0x90, 0x54, 0xc8, 0x8e,
	0x18, 0x88, 0x4e, 0x9f, 0x75, 0x53, 0x1e, 0x0b, 0x6d, 0x52, 0x66, 0x84, 0x92, 0x74, 0x10, 0xd2,
	0xfd, 0x3e, 0x4f, 0x87, 0x24, 0x49, 0x95, 0x51, 0x68, 0x7d, 0x46, 0x44, 0xe6, 0x8b, 0xc8, 0x20,
	0xac, 0x5d, 0x63, 0x3d, 0x21, 0x15, 0xb5, 0xbf, 0x4e, 0x5b, 0xab, 0xc6, 0x2a, 0x56, 0x76, 0x49,
	0x27, 0x2b, 0xbf, 0x7b, 0x23, 0x56, 0x2a, 0xee, 0x72, 0xca, 0x12, 0x41, 0x99, 0x94, 0xca, 0x58,
	0x0b, 0xed, 0x4f, 0x37, 0xda, 0x4a, 0xf7, 0x94, 0xa6, 0x2d, 0xa6, 0xb9, 0x0b, 0x42, 0x07, 0x61,
	0x8b, 0x1b, 0x16, 0xd2, 0x84, 0xc5, 0x42, 0xba, 0x7a, 0xee, 0xd9, 0x3b, 0x45, 0x81, 0x12, 0x96,
	0xb2, 0xde, 0x49, 0x85, 0x7a, 0x51, 0xd5, 0xf4, 0x49, 0x5b, 0xa5, 0x1d, 0xa7, 0xc7, 0x55, 0x88,
	0x9e, 0x4d, 0x72, 0xed, 0x59, 0xd3, 0x88, 0xef, 0xf7, 0xb9, 0x36, 0x58, 0xc0, 0x95, 0x99, 0x5d,
	0x9d, 0x28, 0xa9, 0x39, 0x8a, 0x60, 0xc5, 0x15, 0xbf, 0x0e, 0xd6, 0xc0, 0xad, 0x2b, 0x9b, 0x94,
	0x14, 0x7c, 0x9f, 0xc4, 0x19, 0x35, 0x96, 0x0f, 0xbf, 0xae, 0x96, 0x3e, 0xfc, 0xf8, 0xb4, 0x01,
	0x22, 0xef, 0x84, 0xb7, 0xe1, 0xaa, 0x2d, 0xb5, 0xc3, 0xcd, 0x6e, 0x26, 0xa2, 0x4f, 0x83, 0xaa,
	0xb0, 0x2c, 0x64, 0x87, 0x1f, 0xd8, 0xaa, 0xcb, 0x91, 0xfb, 0x83, 0xdf, 0x02, 0xb8, 0x96, 0xaf,
	0xf4, 0x89, 0x5f, 0xc2, 0xab, 0x59, 0x70, 0x9f, 0xfd, 0x7e, 0xe1, 0xec, 0x59, 0xf3, 0xc6, 0xe5,
	0x09, 0x45, 0x74, 0xca, 0x18, 0x0b, 0x8f, 0xf2, 0xb8, 0xdb, 0xcd, 0x43, 0x69, 0x42, 0xf8, 0xe7,
	0xe2, 0x7d, 0x92, 0x9b, 0xc4, 0x75, 0x09, 0x99, 0x74, 0x09, 0x71, 0xed, 0xea, 0xbb, 0x84, 0xec,
	0xb1, 0x98, 0x7b, 0x6d, 0x34, 0xa5, 0xc4, 0xc7, 0x27, 0xf0, 0x73, 0x6b, 0x9d, 0x09, 0x7f, 0xe9,
	0x42, 0xe0, 0xd1, 0xce, 0x0c, 0xd9, 0x92, 0x25, 0x5b, 0xff, 0x2b, 0x99, 0x4b, 0x3a, 0x8d, 0xb6,
	0xf9, 0xb1, 0x0c, 0xcb, 0x16, 0x0d, 0x7d, 0x06, 0xb0, 0xe2, 0x1a, 0x07, 0x3d, 0x28, 0x1c, 0xf8,
	0x74, 0x37, 0xd7, 0x1e, 0x9e, 0x4f, 0xec, 0xb2, 0xe1, 0xed, 0x37, 0x5f, 0xbe, 0xbf, 0x5f, 0x0a,
	0x11, 0xa5, 0x8b, 0x0d, 0x28, 0xfa, 0x05, 0xe0, 0xca, 0x9c, 0xde, 0x44, 0x4f, 0x16, 0x8b, 0x93,
	0x3f, 0x18, 0xb5, 0xdd, 0xff, 0xe0, 0xe4, 0x29, 0x9b, 0x96, 0xf2, 0x11, 0xaa, 0x17, 0xa3, 0xcc,
	0x5e, 0x3f, 0x7d, 0x65, 0x87, 0xf2, 0x35, 0xfa, 0x09, 0x60, 0xf5, 0xa9, 0xd0, 0xff, 0x4c, 0x9d,
	0x3f, 0x43, 0x8b, 0x52, 0x9f, 0x31, 0x21, 0xb8, 0x6e, 0xa9, 0xef, 0xa1, 0xbb, 0xe7, 0xa3, 0x6e,
	0x34, 0x0f, 0x47, 0x01, 0x38, 0x1a, 0x05, 0xe0, 0xdb, 0x28, 0x00, 0xef, 0xc6, 0x41, 0xe9, 0x68,
	0x1c, 0x94, 0x8e, 0xc7, 0x41, 0xe9, 0xf9, 0xed, 0x59, 0xc3, 0x83, 0x3c, 0x4b, 0x33, 0x4c, 0xb8,
	0x6e, 0x55, 0xec, 0xc7, 0x78, 0xeb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x29, 0x1b, 0x8d,
	0xd5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Individualrecord items.
	GetIndividualrecord(ctx context.Context, in *QueryGetIndividualrecordRequest, opts ...grpc.CallOption) (*QueryGetIndividualrecordResponse, error)
	ListIndividualrecord(ctx context.Context, in *QueryAllIndividualrecordRequest, opts ...grpc.CallOption) (*QueryAllIndividualrecordResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.individualregistration.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetIndividualrecord(ctx context.Context, in *QueryGetIndividualrecordRequest, opts ...grpc.CallOption) (*QueryGetIndividualrecordResponse, error) {
	out := new(QueryGetIndividualrecordResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.individualregistration.v1.Query/GetIndividualrecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListIndividualrecord(ctx context.Context, in *QueryAllIndividualrecordRequest, opts ...grpc.CallOption) (*QueryAllIndividualrecordResponse, error) {
	out := new(QueryAllIndividualrecordResponse)
	err := c.cc.Invoke(ctx, "/rsuncitychain.individualregistration.v1.Query/ListIndividualrecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Individualrecord items.
	GetIndividualrecord(context.Context, *QueryGetIndividualrecordRequest) (*QueryGetIndividualrecordResponse, error)
	ListIndividualrecord(context.Context, *QueryAllIndividualrecordRequest) (*QueryAllIndividualrecordResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetIndividualrecord(ctx context.Context, req *QueryGetIndividualrecordRequest) (*QueryGetIndividualrecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndividualrecord not implemented")
}
func (*UnimplementedQueryServer) ListIndividualrecord(ctx context.Context, req *QueryAllIndividualrecordRequest) (*QueryAllIndividualrecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIndividualrecord not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.individualregistration.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetIndividualrecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetIndividualrecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetIndividualrecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.individualregistration.v1.Query/GetIndividualrecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetIndividualrecord(ctx, req.(*QueryGetIndividualrecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListIndividualrecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllIndividualrecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListIndividualrecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsuncitychain.individualregistration.v1.Query/ListIndividualrecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListIndividualrecord(ctx, req.(*QueryAllIndividualrecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rsuncitychain.individualregistration.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetIndividualrecord",
			Handler:    _Query_GetIndividualrecord_Handler,
		},
		{
			MethodName: "ListIndividualrecord",
			Handler:    _Query_ListIndividualrecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsuncitychain/individualregistration/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetIndividualrecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetIndividualrecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetIndividualrecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetIndividualrecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetIndividualrecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetIndividualrecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Individualrecord.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllIndividualrecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllIndividualrecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllIndividualrecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllIndividualrecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllIndividualrecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllIndividualrecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Individualrecord) > 0 {
		for iNdEx := len(m.Individualrecord) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Individualrecord[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetIndividualrecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetIndividualrecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Individualrecord.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllIndividualrecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllIndividualrecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Individualrecord) > 0 {
		for _, e := range m.Individualrecord {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetIndividualrecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetIndividualrecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetIndividualrecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetIndividualrecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetIndividualrecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetIndividualrecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Individualrecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Individualrecord.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllIndividualrecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllIndividualrecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllIndividualrecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllIndividualrecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllIndividualrecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllIndividualrecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Individualrecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Individualrecord = append(m.Individualrecord, Individualrecord{})
			if err := m.Individualrecord[len(m.Individualrecord)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
